# Generated by Django 5.0.4 on 2024-04-26 14:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResidentialListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.IntegerField()),
                ('agent', models.IntegerField()),
                ('location', models.IntegerField()),
                ('street_number', models.CharField(max_length=10, null=True)),
                ('street_name', models.CharField(max_length=100, null=True)),
                ('area', models.IntegerField()),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Pending', 'Pending'), ('Rented', 'Rented'), ('Sold', 'Sold'), ('Archived', 'Archived'), ('Valuation', 'Valuation')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('listing_type', models.CharField(choices=[('For Sale', 'For Sale'), ('To Let', 'To Let')], max_length=20)),
                ('bedrooms', models.DecimalField(decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('bathrooms', models.DecimalField(decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('study', models.DecimalField(decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('lounges', models.DecimalField(decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('dining_rooms', models.DecimalField(decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('garages', models.DecimalField(decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('carports', models.DecimalField(decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('property_type', models.CharField(choices=[('Apartment Block', 'Apartment Block'), ('Apartment', 'Apartment'), ('Bed & Breakfast', 'Bed & Breakfast'), ('Building', 'Building'), ('Bungalow', 'Bungalow'), ('Club', 'Club'), ('Cluster', 'Cluster'), ('Compound', 'Compound'), ('Detached', 'Detached'), ('Duet', 'Duet'), ('Duplex', 'Duplex'), ('Equestrian Property', 'Equestrian Property'), ('Farm', 'Farm'), ('Flat', 'Flat'), ('Freehold', 'Freehold'), ('Freestanding', 'Freestanding'), ('Full Floor', 'Full Floor'), ('Garden Cottage', 'Garden Cottage'), ('Gated Estate', 'Gated Estate'), ('Golf Estate', 'Golf Estate'), ('Guest House', 'Guest House'), ('Half Floor', 'Half Floor'), ('Hotel Room', 'Hotel Room'), ('Hotel', 'Hotel'), ('House', 'House'), ('Labour Camp', 'Labour Camp'), ('Leaseback', 'Leaseback'), ('Lodge', 'Lodge'), ('Maisonette', 'Maisonette'), ('Package Home', 'Package Home'), ('Penthouse', 'Penthouse'), ('Retirement Unit', 'Retirement Unit'), ('Room', 'Room'), ('Sectional Title', 'Sectional Title'), ('Semi Detached', 'Semi Detached'), ('Simplex', 'Simplex'), ('Small Holding', 'Small Holding'), ('Studio Apartment', 'Studio Apartment'), ('Townhouse', 'Townhouse'), ('Vacant Land', 'Vacant Land'), ('Villa', 'Villa')], max_length=50)),
                ('description', models.TextField()),
                ('publish_street_address', models.BooleanField()),
                ('floor_size', models.DecimalField(decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('floor_size_measurement_type', models.CharField(choices=[('Square Metres', 'Square Metres'), ('Square Feet', 'Square Feet')], max_length=20)),
                ('land_size', models.DecimalField(decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('land_size_measurement_type', models.CharField(choices=[('Square Metres', 'Square Metres'), ('Hectares', 'Hectares'), ('Square Feet', 'Square Feet'), ('Acres', 'Acres')], max_length=20)),
                ('header_images', models.JSONField(default=list, null=True)),
                ('listing_images', models.JSONField(default=list, null=True)),
                ('floor_plans', models.JSONField(default=list, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ListingEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='Propertiez.co.za', max_length=30)),
                ('source_ref', models.CharField(default='e36ef6e1-be37-44ca-94d1-3308b7905b8d', max_length=100)),
                ('user_types', models.JSONField(default=list, null=True)),
                ('source_description', models.CharField(default='Portal', max_length=100)),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('legal_basis', models.CharField(max_length=200, null=True)),
                ('status', models.CharField(default='no_consent', max_length=50)),
                ('message', models.TextField(default='Hi, I am interested in learning more about this property.')),
                ('cell_number', models.CharField(max_length=10, null=True)),
                ('areas', models.JSONField(default=list, null=True)),
                ('suburbs', models.JSONField(default=list, null=True)),
                ('property_types', models.JSONField(default=list, null=True)),
                ('price_from', models.PositiveIntegerField(null=True)),
                ('price_to', models.PositiveIntegerField(null=True)),
                ('size_from', models.PositiveIntegerField(null=True)),
                ('size_to', models.PositiveIntegerField(null=True)),
                ('floor_size_from', models.PositiveIntegerField(null=True)),
                ('floor_size_to', models.PositiveIntegerField(null=True)),
                ('erf_size_from', models.PositiveIntegerField(null=True)),
                ('erf_size_to', models.PositiveIntegerField(null=True)),
                ('asking_price', models.PositiveIntegerField(null=True)),
                ('zoning', models.CharField(max_length=50)),
                ('add_to_mailing_list', models.BooleanField(default=False)),
                ('add_to_profiles', models.BooleanField(default=True)),
                ('add_to_leads', models.BooleanField(default=True)),
                ('consent_messages', models.BooleanField(default=False)),
                ('consent_messages_subscribe_date', models.DateTimeField()),
                ('consent_messages_unsubscribe_date', models.DateTimeField()),
                ('consent_calls', models.BooleanField(default=False)),
                ('consent_calls_subscribe_date', models.DateTimeField()),
                ('consent_calls_unsubscribe_date', models.DateTimeField()),
                ('consent_information', models.BooleanField(default=False)),
                ('subscribe_date', models.DateTimeField()),
                ('unsubscribe_date', models.DateTimeField()),
                ('page_url', models.CharField(max_length=200, null=True)),
                ('hubspotutk', models.CharField(max_length=100, null=True)),
                ('listing_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='listings.residentiallisting')),
            ],
        ),
    ]
