# Generated by Django 5.0.4 on 2024-04-26 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listingenquiry',
            old_name='listing_id',
            new_name='listing',
        ),
        migrations.AddField(
            model_name='listingenquiry',
            name='propdata_id',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='residentiallisting',
            name='propdata_id',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
