# Generated by Django 5.0.4 on 2024-04-26 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_rename_listing_id_listingenquiry_listing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingenquiry',
            name='message',
            field=models.TextField(blank=True, default='Hi, I am interested in learning more about this property.', null=True),
        ),
        migrations.AlterField(
            model_name='listingenquiry',
            name='status',
            field=models.CharField(default='no_consent', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='residentiallisting',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='residentiallisting',
            name='floor_size_measurement_type',
            field=models.CharField(choices=[('Square Metres', 'Square Metres'), ('Square Feet', 'Square Feet')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='residentiallisting',
            name='land_size_measurement_type',
            field=models.CharField(choices=[('Square Metres', 'Square Metres'), ('Hectares', 'Hectares'), ('Square Feet', 'Square Feet'), ('Acres', 'Acres')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='residentiallisting',
            name='publish_street_address',
            field=models.BooleanField(default=True),
        ),
    ]
