# Generated by Django 5.0.4 on 2024-04-29 09:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
        ('listings', '0004_alter_listingenquiry_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='residentiallisting',
            name='propdata_id',
        ),
        migrations.AlterField(
            model_name='listingenquiry',
            name='add_to_leads',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='listingenquiry',
            name='add_to_mailing_list',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='listingenquiry',
            name='add_to_profiles',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='listingenquiry',
            name='areas',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='listingenquiry',
            name='asking_price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listingenquiry',
            name='cell_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='listingenquiry',
            name='consent_calls',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='listingenquiry',
            name='consent_calls_subscribe_date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='listingenquiry',
            name='consent_calls_unsubscribe_date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='listingenquiry',
            name='consent_information',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='listingenquiry',
            name='consent_messages',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='listingenquiry',
            name='consent_messages_subscribe_date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='listingenquiry',
            name='consent_messages_unsubscribe_date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='listingenquiry',
            name='erf_size_from',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listingenquiry',
            name='erf_size_to',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listingenquiry',
            name='floor_size_from',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listingenquiry',
            name='floor_size_to',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listingenquiry',
            name='hubspotutk',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='listingenquiry',
            name='listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='listings.residentiallisting'),
        ),
        migrations.AlterField(
            model_name='listingenquiry',
            name='page_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='listingenquiry',
            name='price_from',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listingenquiry',
            name='price_to',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listingenquiry',
            name='property_types',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='listingenquiry',
            name='size_from',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listingenquiry',
            name='size_to',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listingenquiry',
            name='source_description',
            field=models.CharField(blank=True, default='Portal', max_length=100),
        ),
        migrations.AlterField(
            model_name='listingenquiry',
            name='subscribe_date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='listingenquiry',
            name='suburbs',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='listingenquiry',
            name='unsubscribe_date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='listingenquiry',
            name='user_types',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='listingenquiry',
            name='zoning',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='residentiallisting',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agents.agent'),
        ),
        migrations.AlterField(
            model_name='residentiallisting',
            name='floor_plans',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='residentiallisting',
            name='floor_size',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='residentiallisting',
            name='floor_size_measurement_type',
            field=models.CharField(blank=True, choices=[('Square Metres', 'Square Metres'), ('Square Feet', 'Square Feet')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='residentiallisting',
            name='header_images',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='residentiallisting',
            name='land_size',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='residentiallisting',
            name='land_size_measurement_type',
            field=models.CharField(blank=True, choices=[('Square Metres', 'Square Metres'), ('Hectares', 'Hectares'), ('Square Feet', 'Square Feet'), ('Acres', 'Acres')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='residentiallisting',
            name='listing_images',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
