# Generated by Django 5.0.4 on 2024-04-29 12:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_remove_residentiallisting_propdata_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropDataIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_id', models.PositiveIntegerField(max_length=20)),
                ('branch_id', models.PositiveIntegerField(max_length=20)),
                ('location_id', models.PositiveIntegerField(max_length=20)),
                ('area_id', models.PositiveIntegerField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='residentiallisting',
            name='location',
        ),
        migrations.RemoveField(
            model_name='residentiallisting',
            name='study',
        ),
        migrations.AddField(
            model_name='residentiallisting',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='residentiallisting',
            name='province',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='residentiallisting',
            name='studies',
            field=models.DecimalField(decimal_places=1, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='residentiallisting',
            name='suburb',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='residentiallisting',
            name='area',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='residentiallisting',
            name='bathrooms',
            field=models.DecimalField(decimal_places=1, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='residentiallisting',
            name='bedrooms',
            field=models.DecimalField(decimal_places=1, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='residentiallisting',
            name='carports',
            field=models.DecimalField(decimal_places=1, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='residentiallisting',
            name='dining_rooms',
            field=models.DecimalField(decimal_places=1, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='residentiallisting',
            name='garages',
            field=models.DecimalField(decimal_places=1, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='residentiallisting',
            name='lounges',
            field=models.DecimalField(decimal_places=1, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
