# Generated by Django 5.0.4 on 2024-04-29 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_propdataintegration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propdataintegration',
            name='agent_id',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='propdataintegration',
            name='area_id',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='propdataintegration',
            name='branch_id',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='propdataintegration',
            name='location_id',
            field=models.PositiveIntegerField(),
        ),
    ]
