# Generated by Django 5.0.4 on 2024-04-29 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_alter_propdataintegration_agent_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residentiallisting',
            name='area',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='residentiallisting',
            name='suburb',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
