# Generated by Django 5.0.4 on 2024-04-29 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_alter_residentiallisting_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residentiallisting',
            name='province',
            field=models.CharField(choices=[('Eastern Cape', 'Eastern Cape'), ('Free State', 'Free State'), ('Gauteng', 'Gauteng'), ('KwaZulu-Natal', 'KwaZulu-Natal'), ('Limpopo', 'Limpopo'), ('Mpumalanga', 'Mpumalanga'), ('Northern Cape', 'Northern Cape'), ('North West', 'North West'), ('Western Cape', 'Western Cape')], max_length=100, null=True),
        ),
    ]
