# Generated by Django 5.0.4 on 2024-04-29 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_alter_residentiallisting_province'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='residentiallisting',
            name='branch',
        ),
    ]
