# Generated by Django 5.0.4 on 2024-05-02 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0012_listingimage_residential_listing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='residentiallisting',
            name='floor_plans',
        ),
        migrations.RemoveField(
            model_name='residentiallisting',
            name='listing_images',
        ),
    ]
