# Generated by Django 5.0.4 on 2024-05-02 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0013_remove_residentiallisting_floor_plans_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingimage',
            name='residential_listing',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='listing_images', to='listings.residentiallisting'),
        ),
    ]
