# Generated by Django 5.0.4 on 2024-05-07 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0014_alter_listingimage_residential_listing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingenquiry',
            name='add_to_leads',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='listingenquiry',
            name='add_to_profiles',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='listingenquiry',
            name='consent_calls_subscribe_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listingenquiry',
            name='consent_calls_unsubscribe_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listingenquiry',
            name='consent_messages_subscribe_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listingenquiry',
            name='consent_messages_unsubscribe_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listingenquiry',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.residentiallisting'),
        ),
    ]
