# Generated by Django 5.0.4 on 2024-05-07 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0016_alter_listingenquiry_subscribe_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingenquiry',
            name='propdata_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
