# Generated by Django 5.0.4 on 2024-06-24 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0004_remove_agent_agency_remove_agent_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='agency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='agents.agency'),
            preserve_default=False,
        ),
    ]
