# Generated by Django 5.0.4 on 2024-06-24 13:46

import agents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0006_remove_agent_integrations'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agency',
            options={'verbose_name_plural': 'Agencies'},
        ),
        migrations.AddField(
            model_name='agent',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=agents.models.agent_image_upload_to),
        ),
    ]
