# Generated by Django 5.0.4 on 2024-07-10 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0007_alter_agency_options_agent_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='agent',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='agents', to='agents.tag'),
        ),
    ]
