# Generated by Django 5.0.4 on 2024-04-26 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_alter_listingenquiry_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingenquiry',
            name='message',
            field=models.TextField(blank=True, default="Hi, I'm interested in learning more about this property.", null=True),
        ),
    ]
