# Generated by Django 5.0.4 on 2024-04-30 08:53

import listings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_remove_residentiallisting_branch'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingFloorplan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=listings.models.listing_image_upload_to)),
            ],
        ),
        migrations.CreateModel(
            name='ListingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=listings.models.listing_image_upload_to)),
            ],
        ),
        migrations.RemoveField(
            model_name='residentiallisting',
            name='header_images',
        ),
        migrations.AddField(
            model_name='residentiallisting',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to=listings.models.listing_image_upload_to),
        ),
        migrations.AddField(
            model_name='residentiallisting',
            name='post_code',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='residentiallisting',
            name='floor_plans',
        ),
        migrations.RemoveField(
            model_name='residentiallisting',
            name='listing_images',
        ),
        migrations.AddField(
            model_name='residentiallisting',
            name='floor_plans',
            field=models.ManyToManyField(blank=True, to='listings.listingfloorplan'),
        ),
        migrations.AddField(
            model_name='residentiallisting',
            name='listing_images',
            field=models.ManyToManyField(blank=True, to='listings.listingimage'),
        ),
    ]
