# Generated by Django 5.0.4 on 2024-05-07 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0017_alter_listingenquiry_propdata_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingenquiry',
            name='status',
            field=models.CharField(default='no_consent', max_length=100, null=True),
        ),
    ]
