# Generated by Django 5.0.4 on 2024-05-30 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0019_alter_residentiallisting_property_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='residentiallisting',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
