# Generated by Django 5.0.4 on 2024-05-30 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0020_residentiallisting_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingenquiry',
            name='is_prequalified',
            field=models.BooleanField(default=False),
        ),
    ]
