# Generated by Django 5.0.4 on 2024-06-21 10:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0021_listingenquiry_is_prequalified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residentiallisting',
            name='bathrooms',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='residentiallisting',
            name='bedrooms',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='residentiallisting',
            name='carports',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='residentiallisting',
            name='dining_rooms',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='residentiallisting',
            name='garages',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='residentiallisting',
            name='lounges',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='residentiallisting',
            name='property_type',
            field=models.CharField(choices=[('Apartment Block', 'Apartment Block'), ('Apartment', 'Apartment'), ('Bed & Breakfast', 'Bed & Breakfast'), ('Building', 'Building'), ('Bungalow', 'Bungalow'), ('Club', 'Club'), ('Cluster', 'Cluster'), ('Commercial', 'Commercial'), ('Compound', 'Compound'), ('Detached', 'Detached'), ('Duet', 'Duet'), ('Duplex', 'Duplex'), ('Equestrian Property', 'Equestrian Property'), ('Farm', 'Farm'), ('Flat', 'Flat'), ('Freehold', 'Freehold'), ('Freestanding', 'Freestanding'), ('Full Floor', 'Full Floor'), ('Garden Cottage', 'Garden Cottage'), ('Gated Estate', 'Gated Estate'), ('Golf Estate', 'Golf Estate'), ('Guest House', 'Guest House'), ('Half Floor', 'Half Floor'), ('Hotel Room', 'Hotel Room'), ('Hotel', 'Hotel'), ('House', 'House'), ('Industrial', 'Industrial'), ('Labour Camp', 'Labour Camp'), ('Leaseback', 'Leaseback'), ('Lodge', 'Lodge'), ('Maisonette', 'Maisonette'), ('Office', 'Office'), ('Package Home', 'Package Home'), ('Penthouse', 'Penthouse'), ('Retirement Unit', 'Retirement Unit'), ('Room', 'Room'), ('Sectional Title', 'Sectional Title'), ('Semi Detached', 'Semi Detached'), ('Simplex', 'Simplex'), ('Small Holding', 'Small Holding'), ('Studio Apartment', 'Studio Apartment'), ('Townhouse', 'Townhouse'), ('Vacant Land', 'Vacant Land'), ('Villa', 'Villa'), ('Warehouse', 'Warehouse')], max_length=50),
        ),
        migrations.AlterField(
            model_name='residentiallisting',
            name='studies',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
