# Generated by Django 5.0.4 on 2024-04-29 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('enabled', models.BooleanField(default=False)),
                ('api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('agent_id', models.CharField(blank=True, max_length=50, null=True)),
                ('branch_id', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contact_number', models.CharField(max_length=15, unique=True)),
                ('ffc_id', models.CharField(max_length=20, unique=True)),
                ('agency', models.CharField(max_length=50)),
                ('branch', models.CharField(max_length=50)),
                ('integrations', models.ManyToManyField(blank=True, to='agents.integration')),
            ],
        ),
    ]
