# Generated by Django 5.0.4 on 2024-05-30 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='publish_agent',
            field=models.BooleanField(default=True),
        ),
    ]
