# Generated by Django 5.0.4 on 2024-05-24 10:49

import django.db.models.deletion
import ibuy.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='iBuyProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('id_number', models.PositiveIntegerField(validators=[ibuy.models.validate_id_number])),
                ('phone_number', models.CharField(max_length=20, validators=[ibuy.models.validate_phone_number])),
                ('email_address', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=150)),
                ('num_bedrooms', models.PositiveSmallIntegerField()),
                ('num_bathrooms', models.PositiveSmallIntegerField()),
                ('num_lounges', models.PositiveSmallIntegerField()),
                ('num_garages', models.PositiveSmallIntegerField()),
                ('expected_price', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='iBuyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=ibuy.models.ibuy_image_upload_to)),
                ('ibuy_submission', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='ibuy_images', to='ibuy.ibuyproperty')),
            ],
        ),
    ]
